from typing import List

WIDTH = 800
HEIGHT = 600

COORDINATE = List[int]
VELOCITY = List[float]
SIZE = COORDINATE

# Display state constants
FPS = 60

# Game state constants
INITIAL_LIVES = 3
INITIAL_SCORE = 0

# ASTEROID constants
ASTEROID_ACC_MULTIPLIER = .2
ASTEROID_ACC_ADJUSTMENT = .1
ASTEROID_SPAWN_MIN_COUNT = 2
ASTEROID_SPAWN_MIN_DISTANCE = 100
ASTEROID_VELOCITY_MULTIPLIER = .6
ASTEROID_VELOCITY_ADJUSTMENT = .3

# Ship constants
SHIP_THRUST_FADE_IN_TIME = 500
SHIP_THRUST_FADE_OUT_TIME = 1000
SHIP_THRUST_MULTIPLIER = .1
SHIP_TURN_SPEED = 2
SHIP_VELOCITY_MULTIPLIER = .98


# Missile constants
MISSILE_SIZE = 10
MISSILE_SPEED = 6

# Sound constants
SOUNDTRACK_FADE_IN_TIME = 500
SOUNDTRACK_FADE_OUT_TIME = 1500

# Other constants
DEBRIS_SCROLL_SPEED = 0.25
SPAWN_ROCK_EVENT_INTERVAL = 2000